import { Animal } from './animal';

export const ANIMALS: Animal[] = [
    { id: 1, name: 'Cat', race: 'Birman', size: 'Small', weight: '4kg', origin: 'Burma', description: 'The sacred of Burma or Burmese, is a breed of cats native to Burma. This medium-sized cat is characterized by its medium-length coat, which has the same colourpoint pattern as the Siamese but its feet are pure white as if it had gloves.', picture: 'http://www.chat-birman.fr/elevage-sacre-birmanie/images/stories/May-Eya/img_7297%201280x692.jpg', gender: 'Male', nutriment: '', lat: 16.8052800, lng :96.1561100},
    { id: 2, name: 'Dog', race: 'Golden Retriever', size: 'Small', weight: '30kg', origin: 'Great-Britain', description: 'The golden retriever or simply golden is a breed of dog of British origin. Selected as a report dog, the golden retriever is a very popular breed since the 1990s. It is a medium-sized dog with a long-haired, cream to dark golden color.', picture: 'http://blog.dogfidelity.com/wp-content/uploads/2015/12/golden-retriever.jpg', gender: 'Female', nutriment: '' , lat: 51.5085300, lng : -0.1257400},
    { id: 3, name: 'Horse', race: 'Caspian', size: 'Large', weight: '200kg', origin: 'Iran', description: 'Caspian horses posses several characteristics that differ from modern breeds, such as the shape of the scapula, which is wider at the base than at the top and an extra molar in the top jaw. The Caspian is very similar to an Arabian in appearance with large almond shaped eyes and small but graceful tipped-in ears. All solid colors are common. The breed stands 10 to 12 hands.', picture: 'http://nordiclights.se/wp-content/uploads/2015/08/15NL-015F-03.jpg', gender: 'Male', nutriment: '' , lat: 43.3097200, lng :44.0861400},
    { id: 4, name: 'Cow', race: 'Charolaise', size: 'Large', weight: '1700kg', origin: 'France', description: 'The Charolais is a French cattle breed originating from the region of Charolles in Burgundy, dedicated mainly to the production of meat, whose individuals are of large size and of plain white color sometimes drawing towards the cream.Providing a low-fat meat and good taste, it is renowned for its butcher qualities but also for its strong growth, hardiness and docility. This breed is widely used in crossbreeding with dairy or local breeds to improve the calf\'s conformation.', picture: 'http://charolais-jubert.fr/wp-content/uploads/2011/09/Gondole.jpg', gender: 'Female', nutriment: '' , lat: 48.8534100, lng :2.3488000},
    { id: 5, name: 'Goat', race: 'Dwarf', size: 'Small', weight: '5kg', origin: 'Senegal', description: 'The dwarf goat is a breed of goats used primarily as a pet. Indeed, this animal has an attaching, social and affectionate character. She can live about 14 years.', picture: 'http://partage-images.net/IMG/jpg/DSC_0011.jpg', gender: 'Male', nutriment: '' , lat: 14.6937000, lng :-17.4440600},
    { id: 6, name: 'Lion', race: 'Lion', size: 'Large', weight: '350kg', origin: 'Africa', description: 'The lion (Panthera leo) is a species of carnivorous mammals of the felidae family. The female of the lion is the lioness, her cub is the lion. The adult male, easily recognizable by its large mane, has an average mass which can vary according to the geographical zones in which it occurs, ranging from 180 kg for the Kruger lions to 230 kg for the Transvaal lions. Some very rare specimens may exceptionally exceed 250 kg. An adult male feeds on 7 kg of meat each day and 5 kg on the female. The lion is a gregarious animal, that is to say that it lives in large family groups, unlike other felines. Its life expectancy in the wild is between 7 and 12 years for the male and 14 to 20 years for the female, but it frequently exceeds 30 years in captivity.', picture: 'http://www.thehumanzootheatrecompany.co.uk/uploads/1/9/3/7/19374849/__5937257_orig.jpg', gender: 'Male', nutriment: '' , lat: 7.18805555556, lng : 21.0936111111}
  ];
